# Generated by Django 4.0.4 on 2022-05-24 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('m_type', models.CharField(choices=[('Free', 'Free'), ('MM Bundle Monthly', 'MMB1M'), ('MM Bundle Quarterly', 'MMB3M'), ('MM Bundle Semestral', 'MMB6M'), ('MM Bundle Yearly', 'MMB1Y')], default='Free', max_length=30)),
                ('m_price', models.IntegerField(default=0)),
                ('stripe_plan_id', models.CharField(default='noplan', max_length=40)),
                ('old_stripe_plan_id', models.CharField(default='nooldplan', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=40)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.membership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(default='', max_length=40)),
                ('sub_active', models.BooleanField(default=False)),
                ('user_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermembership')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_inviteonly', models.CharField(default='', max_length=50)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.membership')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipMT5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt5_ea_name', models.CharField(default='', max_length=50)),
                ('is_mt5', models.BooleanField(default=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.membership')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipDiscord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_private', models.BigIntegerField(default=0, max_length=50)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.membership')),
            ],
        ),
    ]
